### ISSUE TITLE
Проблема с отображением в котором часу мы остановили видео

### ISSUE THREAD

**Issue by norraxx** [anilibria/anilibria-app#1]
Если я остановлю видео спустя час, программа запоминает в который момент я его остановил. Но время остановки видео она отображает без часов, только минуты и секунды.
https://github.com/anilibria/anilibria-app/blob/d775889b013512a3b0180693706613228b602190/app/src/main/java/ru/radiationx/anilibria/ui/adapters/release/detail/ReleaseEpisodeDelegate.kt#L65

Предлогаемое решение:
Добавить час к форматированию
https://github.com/anilibria/anilibria-app/blob/5acbaf39820473bc0cb348106601bb9605f49fbb/app/src/main/java/ru/radiationx/anilibria/extension/Date.kt#L12 `"HH:mm:ss"`

**Comment by RadiationX** [comment]
Справедливо. Исправим

**Comment by RadiationX** [comment]
https://github.com/anilibria/anilibria-app/commit/60d1dd9e65f4cf28eb4160b0b1fe01776f12d65d
