### ISSUE TITLE
Добавить в приложение magnet ссылки

### ISSUE THREAD

**Issue by kirill-782** [anilibria/anilibria-app#100]
Предлагаю добавить в раздел с торрент файлами помимо возможности загрузить torrent файл возможность сразу добавить в клиент торрент по magnet ссылке. Таким образом можно будет исключить браузер из цепочки. 

Реализовать можно либо отдельной кнопкой, либо переключателем в настройках

**Comment by RadiationX** [comment]
В релизе 2.10.0 сделал загрузку торрент-файлов внутри приложения. 
С разными торрент клиентами проверил - везде файл открывается сразу.
