### ISSUE TITLE
Баг с датой последнего обновления тайтлов (1970 год)

### ISSUE THREAD

**Issue by phoriah** [anilibria/anilibria-app#101]
Присутствует лишь у некоторых (пока только нашёл один)

`О моём перерождении в слизь`

Как на Android так и на Android Tv
![ScreenshotAniLibria App.jpg](https://github.com/anilibria/anilibria-app/assets/95628489/6d41633c-dd87-4541-8d15-406e949734c2)

**Comment by RadiationX** [comment]
Будет исправлено в следующем релизе 2.9.x на днях
