### ISSUE TITLE
TrojanScript/Wacatac.Html detected in TV ver 1.1.0

### ISSUE THREAD

**Issue by A-Kolotsey** [anilibria/anilibria-app#107]
Microsoft Defender в Windows 10 удаляет AniLibria_TV_v1.1.0.apk
и сообщает, что в нем найден вирус
![image](https://github.com/anilibria/anilibria-app/assets/72033647/cf211eee-77b8-47a0-b603-36db5c414ad6)

В версии AniLibria_TV_v1.1.0_RC1.apk вирусов не находит.

**Comment by RadiationX** [comment]
Похоже на ложное срабатывание, похоже на этот случай https://answers.microsoft.com/ru-ru/windows/forum/all/ложное/2292e6cd-7548-447c-8616-1210cf39a283. 

Даже представить не могу, что могло триггернуть антивирус, особой разницы между RC1 и финальной версией нет.

**Comment by ThIsLinked** [comment]
@RadiationX здрасьте. Можно какой-нибудь мессенджер? Телега там или что-то такое. Есть пара вопросов, а трепать об этом... в Issues? как-то странно. Если что, я ThIsLinked (на всякий).

**Comment by RadiationX** [comment]
Проверил апк на вирусы, вроде всё, так что issue закрываю
1.1.0: https://www.virustotal.com/gui/file/14c9603b9abf795f765280814459b9fadb0f3fe70af913a2912abfd59d9cc145
1.2.0: https://www.virustotal.com/gui/file/970e3c9bf298d56eda29aeed1a7d15fdea75a2bd875099c86dc927ca2b439e1e

**Comment by ThIsLinked** [comment]
@RadiationX 
Да забей. Это не антивирус, а шорутра программная. Недавно на Aurora Store агрился потому что ему META-INF не нравился.
