### ISSUE TITLE
Глюк при подключении клавы на планшете

### ISSUE THREAD

**Issue by LuckyBoyE14** [anilibria/anilibria-app#11]
планшет samsung tab S5e. при подключении клавиатуры (притом официальной, Чехол Keyboard Cover Galaxy Tab S5e). начинает сбрасывать видео иногда на начало, иногда на 1 серию. соответственно, когда случайно задеваешь планшет, то такое поведение начинает бесить. Пытался выловить баг в других приложениях, даже качал AnimeBest, но все работает нормально.

P.S. Добавьте настройку, чтобы можно было убрать автовоспроизведение видео по окончанию серии, а то батарея садится, когда с телефоном засыпаешь.

**Comment by RadiationX** [comment]
Есть возможность записать видео или скринкаст как это происходит? (видео можно на ютуб залить и дать доступ по ссылке)

**Comment by LuckyBoyE14** [comment]
> Есть возможность записать видео или скринкаст как это происходит? (видео можно на ютуб залить и дать доступ по ссылке)

Записал, но воспроизвести баг, когда еще и на первую самую серию сбрасывается не получилось. Только сброс в начало видео.

ссылка:
https://youtu.be/b4auP8trJwE

**Comment by LuckyBoyE14** [comment]
miss click

**Comment by RadiationX** [comment]
Проблема еще актуальна?

**Comment by RadiationX** [comment]
Вероятно баг был исправлен, когда было исправлено сохранении точки остановки серии.
