### ISSUE TITLE
Невозможно пользоваться приложением на Android TV

### ISSUE THREAD

**Issue by IvanDelete** [anilibria/anilibria-app#12]
приставка Xiaomi MI Box S, не все важные элементы приложения поддерживают навигацию с помощью пульта, отчего просто невозможно(с пульта) запустить воспроизведение любого видео

**Comment by IvanDelete** [comment]
нерелевантно, оказывается имеется отдельное приложение для тв

**Comment by RadiationX** [comment]
У нас еще и под другие платформы есть приложения :) https://anilibria.app
