### ISSUE TITLE
Запуск установочного apk файла

### ISSUE THREAD

**Issue by PhysicalChief** [anilibria/anilibria-app#130]
Добрый день. При запуске apk файла на установку приложения не происходит никакой реакции, при повторной попытке установки неизвестная ошибка и информация о сервисе установки пакетов.
Телефон pixel 8 pro, android 14, версия ядра 5.15.110-android14-11-gcc48824eebe8-ab10865596
#1 Tue Sep 26 19:57:58 UTC 2023
Номер сборки UQ1A.231205.015

**Comment by ismaslov** [comment]
Подтверждаю, на p8p не ставится

**Comment by ismaslov** [comment]
но есть и хорошие новости. Если ставить через приложение Files, то всё ок!

**Comment by RadiationX** [comment]
Не очень понятно, проблема при установке обновления из приложения AniLibria? 
Или это в целом ошибка при установке apk файла?

**Comment by ismaslov** [comment]
При начальной установке из apk. Но анилибрия, на проверку, оказалось не единственным приложением которое не ставится сходу на p8p

**Comment by RadiationX** [comment]
Понял, спасибо. В таком случае закрываю issue.
