### ISSUE TITLE
Предложение по кнопке торрент

### ISSUE THREAD

**Issue by Slavatar2001** [anilibria/anilibria-app#134]
Мне нужны торрент файлы к аниме, ну сейчас на кнопке магнитная ссылка на андроид. И скачивать приходится с сайта.
Добавьте либо при нажатии "скачать торрент файл", или "скачивать по магнитной ссылке", и там же галочку "запомнить выбор".
Или же в приложении там где торрент серии, добавить кнопки иконок "торрент" и кнопку "магнит" , как обычно на форумах.
Прошу вас,и спасибо 😉

**Comment by RadiationX** [comment]
Ок, что-нибудь придумаю)
