### ISSUE TITLE
Загрузка доступных адресов очень долгая

### ISSUE THREAD

**Issue by Arcane97** [anilibria/anilibria-app#14]
Шла около минуты, сначала подумал, что приложение зависло

**Comment by RadiationX** [comment]
А приложение было установлено с нуля или поверх старого?
Какой оператор/провайдер?
Проблема повторяется?

**Comment by Arcane97** [comment]
Проблема встретилась при обновлении приложения. Полностью удалил приложение и заново скачал. 
Провайдер Ufanet.
Да, проблема повторилась, когда на перепрошитый телефон (Xiaomi Redmi Note 5) заново ставил приложение.

Как я понял, эта загрузка идёт при первом запуске приложения.
При следующих запусках, данной загрузки не встречал.

**Comment by Arcane97** [comment]
![Screenshot_2021-02-08-23-17-12-949_ru radiationx anilibria app](https://user-images.githubusercontent.com/34447979/107263840-0fd7b200-6a64-11eb-984f-14f87f49df6c.jpg)
![Screenshot_2021-02-08-23-17-36-467_ru radiationx anilibria app](https://user-images.githubusercontent.com/34447979/107263844-1108df00-6a64-11eb-9ff6-d5b006f0a58b.jpg)

**Comment by Arcane97** [comment]
Загрузка списка адресов шла примерно минуту

**Comment by RadiationX** [comment]
Понял, спасибо

**Comment by RadiationX** [comment]
Можете проверить эту тестовую версию? Стало лучше?
https://github.com/anilibria/anilibria-app/releases/download/2.4.8/AniLibria_v2.4.8_RC1.apk

**Comment by Arcane97** [comment]
Да, стало лучше, заметно быстрее.

**Comment by RadiationX** [comment]
Хорошо, спасибо. Тогда на днях раскачу обновление на всех

**Comment by RadiationX** [comment]
Исправлено
