### ISSUE TITLE
Обновление списка на главной странице Android TV

### ISSUE THREAD

**Issue by wnex** [anilibria/anilibria-app#15]
Здравствуйте. Добавьте пожалуйста какую либо кнопку для обновления списка на главной в приложении для android tv. Сейчас если выходят новые серии, чтобы их увидеть в списке надо остановить приложение через настройки. Это очень неудобно.

**Comment by RadiationX** [comment]
Есть примеры, где такое удобно реализовано?
При разработке приложения я не смог найти ничего подходящего. Там или всегда перезагружался экран или так-же кешировался.

Ну и не обязательно останавливать приложение, достаточно просто закрыть его кнопкой "назад"

**Comment by wnex** [comment]
Обычно при переходе по вкладкам слева происходит обновление контента. Например у кранчирол так. Либо кнопку обновить, где-нибудь рядом с поиском.

Через кнопку "назад" действительно удобней, но это надо знать.

**Comment by RadiationX** [comment]
А то, что при обновлении экрана может теряться фокус у элементов, это не напрягает?
Например в ленте загрузили несколько "страниц" и при переходе между вкладками это сбросится. Кажется это не очень удобно

**Comment by RadiationX** [comment]
В ближайшем обновлении будет сделано. Обновление будет происходить при каждом открытии экрана, т.е. например при переключении между "главная" и "я смотрю" или при возвращении назад на экран.

Будет возможность проверить на тестовой сборке?

**Comment by wnex** [comment]
Спасибо. Могу проверить, где скачать тестовую сборку?

**Comment by RadiationX** [comment]
Можно из телеграм чата, для более быстрого фидбека https://t.me/anilibria_app_tester
Либо с гитхаба https://github.com/anilibria/anilibria-app/releases/tag/tv-1.1.0-rc1

**Comment by wnex** [comment]
Вроде нормально все работает. Проблемы только если обновление происходит на промотанном списке, позиция промотки не сохраняется. И не работает кнопка веб-плеер, ничего не происходит при нажатии.

**Comment by RadiationX** [comment]
Исправлено: https://github.com/anilibria/anilibria-app/releases/tag/tv-1.1.0
