### ISSUE TITLE
Заменить кнопку смотреть на тег разрешения

### ISSUE THREAD

**Issue by AAAYaKo** [anilibria/anilibria-app#153]
Раньше были 3 отдельные кнопки и было видно какое максимальное разрешение доступно и находится ли только что вышедшая серия в процессе выкладки (тк разрешения появлялись постепенно)
Надпись смотреть же не несёт как таковой информационной нагрузки
Предлагаю убрать эту надпись и заменить её на тег SD/HD/FullHD в зависимости от максимального доступного разрешения
Так же интересно 3 вопроста, не знаю где ещё задать
1) h265 варианты транскодятся из h264? Интересует на случай, если захочу кое что скачать и сам перекодить в h265/vp9/av1
2) стримминг идёт только в h264? Он может идти в h265?
3) по какой причине убрали возможность использовать внешний плеер?

**Comment by RadiationX** [comment]
На счет надписи подумаю.

1. Да, на сколько мне известно, h265 кодится из h264, не на gpu.
2. Сейчас только h264.
3. 
3.1. Это создавало проблемы и путаницу у пользователей. 
3.2. Изначально, вроде-бы, это добавлял просто как запасной вариант на случай косяков встроенного плеера.
Сейчас плеер переписан, и потенциальных косяков в нем меньше, а удобств в рамках приложения больше.
3.3. Сегодня еще узнал, что "внешний плеер" использовался для скачивания серий - тоже не хорошо.

**Comment by AAAYaKo** [comment]
А возможно ли добавить стриминг в h265? Допустим для при ограниченном трафике качество будет лучше h265 в fullHD, чем h264 в hd/sd

**Comment by RadiationX** [comment]
Не знаю будут ли это добавлять.
Из технических моментов - кодирование в h265 занимает гораздо больше времени, чем h264. И еще нужно учитывать, что не все устройства имеют аппаратный декодер h265.

Надеюсь когда-нибудь это будет)

**Comment by AAAYaKo** [comment]
Ясно, ну мне казалось приложение умеет понимать есть ли декодер h265
![Screenshot_20240311_135449_AniLibria App](https://github.com/anilibria/anilibria-app/assets/69294541/2c7ea911-4557-4316-bc77-d35002dafe85)
![Screenshot_20240311_135442_AniLibria App](https://github.com/anilibria/anilibria-app/assets/69294541/98b1ab85-6947-4b32-91aa-778863f6d319)
Думал можно стримить выложенную версию h265 если есть версия и поддержка или h264, если нет
Ну, если такой возможности сейчас нет, то ладно

**Comment by LiphiTC** [comment]
> 3.3. Сегодня еще узнал, что "внешний плеер" использовался для скачивания серий - тоже не хорошо.

А что плохого, что использовали для скачивания? 

Я бы вернул фишку с внешним плеером(мне в мпв удобнее смотреть иногда), но чтобы она была не по дефолту.

**Comment by RadiationX** [comment]
@LiphiTC Сервера онлайн плеера должны использоваться по прямому назначению - смотреть в онлайне.
Для скачивания есть торрент.

**Comment by RadiationX** [comment]
> Предлагаю убрать эту надпись и заменить её на тег SD/HD/FullHD в зависимости от максимального доступного разрешения

Всё-таки оставлю как оно есть сейчас, т.к. это практически бесполезная информация, которая только будет только мешать.
