### ISSUE TITLE
Фоновое воспроизведение для встроенного плеера

### ISSUE THREAD

**Issue by AAAYaKo** [anilibria/anilibria-app#155]
Не хватает функции фонового воспроизведения
Раньше со внешним плеером проблемм не было, но если решили его вырезать то хотелось бы, чтобы такая функция была
Разумеется должна быть галочка включить выключить кому-то удобнее так, а кому-то по другому

**Comment by RadiationX** [comment]
Помню такое уже предлагали, но это какая-то странная фича. Аниме не музыка же.
Скорее всего такую функцию добавлять не буду:
1. Аниме не музыка
2. Честно, не вижу смысла делать эту фичу с учетом технической сложности и, вероятно, малой востребованности

**Comment by AAAYaKo** [comment]
Ну, тут не принципиально, так что понимаю,но я этим переодически пользовался, многие плееры видео так умеют
