### ISSUE TITLE
Добавить во встроенный плеер кнопку замок

### ISSUE THREAD

**Issue by AAAYaKo** [anilibria/anilibria-app#157]
Сейчас почти в любом плеере есть кнопка закрытый замок в углу, по нажатию на кторую интерфейс блокируется и скрывается
По нажатию при блокировке показывается только кнопка открытого замка
По нажатию на кнопку интерфейс вновь доступен
![Screenshot_20240311_022008_Video Player](https://github.com/anilibria/anilibria-app/assets/69294541/27d8b982-a1ae-4c91-aab2-34337901cfe2)

При заблокированном интерфейсе желательно также не должны работать действия назад, домой и меню, а так же заблокированна шторка уведомлений

**Comment by RadiationX** [comment]
Может быть в будущем добавлю.
Посмотрел несколько плееров - во всех реализовано по разному.

Ну а блокировать действие назад - плохая практика. Домой, меню и шторку - впринципе невозможно.

**Comment by AAAYaKo** [comment]
Ну последние пункты опционально, но в моём пллере всё это блокируется

**Comment by RadiationX** [comment]
Ну с кнопкой/жестом "назад" еще понятно.
А остальное как может блокироваться? Это же системные штуки, поведение которых переопределить/настроить нельзя.

**Comment by AAAYaKo** [comment]
Тут не подскажу, но для меня это не критично

**Comment by RadiationX** [comment]
Реализовано в https://github.com/anilibria/anilibria-app/releases/tag/2.12.0_RC1

**Comment by RadiationX** [comment]
Доступно в https://github.com/anilibria/anilibria-app/releases/tag/2.12.0
