### ISSUE TITLE
Баг плеера

### ISSUE THREAD

**Issue by TheAbyssII** [anilibria/anilibria-app#161]
![IMG_20240311_112121.jpg](https://github.com/anilibria/anilibria-app/assets/100950127/2e8d6fc2-67b4-4ccd-a8c2-3817b20b5ed7)

**Comment by ArtiomLev** [comment]
Я уже открыл по этому поводу:
https://github.com/anilibria/anilibria-app/issues/160#issue-2178606231

**Comment by RadiationX** [comment]
Сервера плеера штормит слегонца, уже исправляют.
Должно исправиться само через какое-то время.
