### ISSUE TITLE
Исправить перемотку

### ISSUE THREAD

**Issue by ArtiomLev** [anilibria/anilibria-app#162]
В прошлой версии плеера перемотка осуществялась от момента, в котором отпустил палец, а в новом от начала жеста. Может это и удобнее, но, как и много ещё где, при возвращении в 0:00 откидывает воспроизведение назад. А не редко надо отменить жест. Можете исправить, пожалуйста?
Я вижу как варианты решения либо выбор от какого момента отсчитывать в настройках, либо игнорирование 0:00.

**Comment by RadiationX** [comment]
Да, сделаю игнорирование 0:00

**Comment by RadiationX** [comment]
Исправлено https://github.com/anilibria/anilibria-app/releases/tag/2.11.1
