### ISSUE TITLE
Переход в корень вкладки при долгом нажатии иконки

### ISSUE THREAD

**Issue by ArtiomLev** [anilibria/anilibria-app#166]
Можно добавить переход на главную страницу вкладки  (которые там снизу в панели) по удержанию иконки? А то пройдёшь по ссылкам перекрёстным и надо всё это потом назад пролистывать.

**Comment by AAAYaKo** [comment]
Обычно это кст не по удержанию, а по второму тапу работает в других приложениях
Первый наверх страницы, второй в корень влкадки

**Comment by ArtiomLev** [comment]
В принципе да, можно и так

**Comment by RadiationX** [comment]
Реализовано в https://github.com/anilibria/anilibria-app/releases/tag/2.12.0_RC1
Сделал по долгому удержанию + диалог подтверждения

**Comment by RadiationX** [comment]
Доступно в https://github.com/anilibria/anilibria-app/releases/tag/2.12.0
