### ISSUE TITLE
Разблакировка релизов, заблокированных в РФ

### ISSUE THREAD

**Issue by AAAYaKo** [anilibria/anilibria-app#169]
Через приложение сейчас релизы, заблокированные в РФ нельзя посмотреть из любой страны
На сайте такой проблемы нет

**Comment by kirill-782** [comment]
Ох девочка волшебница собрала команду тестеров по поиску багов. Но тут вероятнее всего проблема с API, так что думаю это пофиксят не быстро

**Comment by AAAYaKo** [comment]
Ну я скорее активизировался после отключения стороннего плеера в приложении, но не спорю

**Comment by kirill-782** [comment]
Настрой [торрент стриминг](https://4pda.to/forum/index.php?showtopic=889960) и не парься. У анилибрии довольно живой трекер. Правда если у тебя android

**Comment by AAAYaKo** [comment]
Понятия не имею, зачем ты это написал
1 тогда я уж лучше просто скачаю
2 это вообще не решает проблему приложения

**Comment by Foresteam** [comment]
Оно из Гоголь плея страну подсасывает, или что? В чем проблема просто по IP определять, через любой сайт? Или разрабы цель прям ставили, чтобы аудитория анилибрии с андроида вообще никак не посмотрела? Трижды пожалел уже, что обновил приложение

**Comment by AAAYaKo** [comment]
Нет, я предполагаю, что это связано с ip сервера для масскировки основного сервера anilibria через которое подключается приложение для доступа к api.
Я конечно не лез в репозиторий разбираться, может и не прав
Ну и блокировка не связана последним с обновлением, заблокированными релизы должны быть и на предыдущих версиях

**Comment by RadiationX** [comment]
@Foresteam это и на предыдущих версиях аппки блочится. Это всё на стороне сервера, проблему вроде скоро уже должны решить

**Comment by RadiationX** [comment]
Т.к. проблема исключительно на стороне апи, то закрываю.
Обещали исправить.
