### ISSUE TITLE
Повтор и некорректное отображение списка избранных

### ISSUE THREAD

**Issue by bot08** [anilibria/anilibria-app#17]
Не знаю знаете ли вы о этом баге, но при удалении избранного тайтла с списка избранных, список повторяется и некорректно отображает данные. 
[Вот видео с демонстрацией.](https://youtu.be/YFNimUW1R98)

**Comment by RadiationX** [comment]
Да, помню что-то такое было. Исправим

**Comment by bot08** [comment]
Ок

**Comment by bot08** [comment]
надеюсь поправили

**Comment by RadiationX** [comment]
поправили, только еще не зарелизили
