### ISSUE TITLE
Медиаклавиши запускают фоновое воспроизведение

### ISSUE THREAD

**Issue by AAAYaKo** [anilibria/anilibria-app#170]
Поскольку данную идею благополучно забрили, то надо отрубить управление медиа в фоне
Сейчас при втыкании наушников или нажатии play на медиа клавишах запускается воспроизведение в фоновом режиме, чего быть не должно по плану
Либо доделать, либо отрубить

**Comment by RadiationX** [comment]
Исправлено в https://github.com/anilibria/anilibria-app/releases/tag/2.12.0_RC1

**Comment by RadiationX** [comment]
Доступно в https://github.com/anilibria/anilibria-app/releases/tag/2.12.0
