### ISSUE TITLE
Marital You

### ISSUE THREAD

**Issue by ghost** [anilibria/anilibria-app#171]
Думаю, не будет лишним добавить поддержку Material You, раз иконка приложения стала её поддерживать

**Comment by RadiationX** [comment]
Это скорее всего не будет добавлено

**Comment by AAAYaKo** [comment]
С какой конкретно целью? И с текущей версией material дизайн выглядит нормально
Сейчас важнее было бы поправить дизайн с точки зрения ux/ui
К примеру переверстать окно релиза, чтобы правильно расставить акценты
Чем перепысывать весь UI приложения для добавления новой версии материала, для которой ещё надо и дизайнеров иметь, чтобы они красиво на новый материал перерисовали интерфейс

**Comment by AAAYaKo** [comment]
От изменения версии sdk новый дизайн просто так не появится
Панель выглядит плохо не из-за версии sdk, а из-за простого плохого UI дизайна
Что конкретно ты хочешь увидеть от MD3 в новом приложении, что не отновится к обновлёному гайдлайну, а именно к новой библиотеке?

**Comment by RadiationX** [comment]
@MaxNPC возможно да, но в целом, md3 местами выглядит странно, не давая каких-то прям ощутимых плюсов, при этом добавляя кучу сложностей в реализации и кастомизации.
Палитра на че-то около 20-30 цветов с дополнительным ситуативным подкрашиванием каких-то элементов в рантайме - ну это перебор.

В общем в планах добавлять md3 нет.
