### ISSUE TITLE
 Вертикальный свайп обрабатывается, как перемотка

### ISSUE THREAD

**Issue by AAAYaKo** [anilibria/anilibria-app#173]
Можно сделать и при горизонтальном проигрывании, но в вертикальном это проще за счёт высоты экрана

Сделать ограничение, если дельта перемешения по вертикали больше порогового значения не обрабатывать жест, как нажатие или свайп перемотки

**Comment by RadiationX** [comment]
Не до конца понял что конкретно не так и что нужно сделать.
Но будет исправлен баг, когда явно делаешь вертикальный свайп (и слегонца вбок), то срабатывает перемотка. Нужно будет явно именно начать вести по горизонтали.

**Comment by AAAYaKo** [comment]
Да всё, правильно понял
Сейчас если сделать вертикальный свайп и слегка вбок начнётся перемотка

**Comment by AAAYaKo** [comment]
В конце это просто то, как я обычно блокирую свайпы, можно не обращать на это внимание

**Comment by RadiationX** [comment]
Исправлено в https://github.com/anilibria/anilibria-app/releases/tag/2.12.0_RC1

**Comment by RadiationX** [comment]
Доступно в https://github.com/anilibria/anilibria-app/releases/tag/2.12.0
