### ISSUE TITLE
Выскочил web плеер на заблокированном релизе

### ISSUE THREAD

**Issue by AAAYaKo** [anilibria/anilibria-app#174]
![Screenshot_20240322_151846_AniLibria App](https://github.com/anilibria/anilibria-app/assets/69294541/d48fc1b9-1de7-4ed1-b168-2511b3bf3cad)

**Comment by AAAYaKo** [comment]
Даже сумел запустить воспроизведение через него

**Comment by RadiationX** [comment]
Спасибо, исправим

**Comment by RadiationX** [comment]
Т.к. проблема исключительно на стороне апи, то закрываю.
Обещали исправить.
