### ISSUE TITLE
[bug] плеер в приложениях блокирует просмотр из других стран

### ISSUE THREAD

**Issue by sharkman** [anilibria/anilibria-app#175]
Пытался досмотреть "становясь волшебницей".
В приложении для андройда написано "контент недоступен в РФ".
В приложении для телевизора вообще не загружается ничего.
На сайте, естественно, всё открывается нормально.
Нахожусь в польше.
Почините, пожалуйста плеер в приложениях (геолокация видимо сбоит).

**Comment by RadiationX** [comment]
https://github.com/anilibria/anilibria-app/issues/169
