### ISSUE TITLE
Не работает приложение

### ISSUE THREAD

**Issue by Tinchik** [anilibria/anilibria-app#191]
Недавно(Для кого-то давно) приложение стало выдавать ошибку при поиске прокси сервера, Я решил чуть-чуть 🤏🤏 подождать и дождался работы поиска прокси, НО ничего не загружается, единственное, что работает - это уведомление об ошибке: Неправильный формат данных, может ли кто объяснить мне эту ошибку?
![Screenshot_20240608_230015.jpg](https://github.com/anilibria/anilibria-app/assets/78418943/fe6c0fed-4332-4aa1-b2f5-77554cef5a40)

**Comment by sakebaev** [comment]
У меня так весь день происходит.

**Comment by RadiationX** [comment]
Были проблемы с апи. Уже не актуально.
