### ISSUE TITLE
Добавить кнопку об ошибке в плеер

### ISSUE THREAD

**Issue by AAAYaKo** [anilibria/anilibria-app#194]
Как на сайте добавить в плеер функционал сообщить об ошибке в плеере
Сейчас единственный способ сообщить о повреждённом видео файле - это перейти на сайт и найти релиз

Должно выголядеть, как ещё одна кнопка в меню, по нажатию на которую появляется окно с текстовым полем и кнопкой отправить

Хотелось бы, чтобы в поле заранее был введён текст по шаблону
Дата обращения Релиз: Серия
Возможно, если какие-то ещё технические данные помогут, их можно включить в данный шаблон

**Comment by RadiationX** [comment]
Все ошибки в плеере автоматически собираются и отправлюятся в аналитику.
То, что выводится пользователям в плеере - просто облегчает нам понимание какого рода эта ошибка при обращении в техподдержку.
