### ISSUE TITLE
Пропавшие символы

### ISSUE THREAD

**Issue by AAAYaKo** [anilibria/anilibria-app#196]
Шрифт субтитров в плеере приложения не содержит некоторых символов
Видео скачивал, эти символы есть кодировка нормальная
![Screenshot_20240625_134443_AniLibria App](https://github.com/anilibria/anilibria-app/assets/69294541/3cd87db6-89cc-4763-903d-d1c0c8a113b2)
![Screenshot_20240625_141113_AniLibria App](https://github.com/anilibria/anilibria-app/assets/69294541/d7fb7c25-47e9-4e7c-ba28-fa3273c92a25)
Следует обновить шрифт до последней версии и добавить fallback font с большим количеством символов например NotoSans CJK или какой-то другой с поддержкой большего числа символов unicode

**Comment by RadiationX** [comment]
Субтитры для онлайн плеера "хардкодятся" в видеопоток сразу. Передам технарям, мб поправят и перезальют.

**Comment by AAAYaKo** [comment]
@RadiationX в таком случае, почему титры в поток скачанных видео не хардкодятся?

**Comment by RadiationX** [comment]
@AAAYaKo мб чтобы можно было смотреть в оригинале

**Comment by AAAYaKo** [comment]
@RadiationX ясно, ну хорошо на будущее буду знать, хотя мб было бы не плохо иметь возможность выбирать субтитры во встроеном плеере для слабослышащих или для тех, кому просто хочется картинку без изменений каких-то
