### ISSUE TITLE
Хаотичное поведение списка избранного.

### ISSUE THREAD

**Issue by sakebaev** [anilibria/anilibria-app#205]
Версия приложения Anilibria app 2.13.0
Проверенно на двух устройствах Android с одним и тем же аккаунтом

Действия воспроизведению ошибки:
- Ошибка при добавлении:
1. Выбор любого аниме
2. Нажатие на звезду для добавления в список избранного (цвет звезды меняется с серой на красную)
3. Переход на список избранного 
4. Видим что список не меняется
5. Обновляем список через жест пальцем или перезаход в приложение не забыв убрать его со списка открытых приложений телефона
6. Переходим к списку избранного и видим, что ничего не поменялось
7. переходим к тому же аниме и видим что звезда серого цвета

Ошибка при удалении:
С теми аниме, что как-то смогли попасть в список точно такая же проблема, но наоборот, не ясно когда повезёт убрать их из списка.

Обновление списка происходит само, когда захочет и как захочет. Какие-то добавляются, какие-то удаляются.
Разгодать закономерность в поведении не удалось

Ожидаемое поведение:
1. Визуальное изменение списка при обновлении (через жест пальцем сверху вниз или перевход в приложение)
2. Одеваться реакция цвета звезды в зависимости от статуса аниме (состоит ли оно в списке избранного или отсутствует)
3. Изменение списка должно быть моментально
4. Возможность свободно и легко добавлять аниме в список избранного, а также удалять их

**Comment by RadiationX** [comment]
На сервере накрутили кеширование и теперь оно работает вот так криво :(
Пока-что какого-то решения нет, надеюсь что позже исправят такие моменты.
