### ISSUE TITLE
Зависает плеер [Android TV]

### ISSUE THREAD

**Issue by parzifox** [anilibria/anilibria-app#207]
Зависает плеер на Android TV показывает при загрузке сначала 10:00 / 23:20 потом сбрасывает загрузку и показывает -- / -- меняешь качество 1 - 3 минуты всё нормально идёт потом снова -- / --

**Comment by RadiationX** [comment]
Проверьте, работает ли сейчас?
Ребята сообщают, что всё исправлено https://t.me/anilibria/14805

**Comment by RadiationX** [comment]
Исправлено
