### ISSUE TITLE
Ошибка в плеере 

### ISSUE THREAD

**Issue by King-of-the-noth** [anilibria/anilibria-app#210]
![Screenshot_20240908-044350](https://github.com/user-attachments/assets/c29758c3-3c0a-4754-9855-bd9fb7575154)
Выдает такую ошибку, для наглядности взял рандомное аниме, это ошибка в любом аниме которое я ставлю, что посоветуете сделать?

**Comment by RadiationX** [comment]
Вроде были какие-то проблемы с серверами, сейчас уже всё работает)
