### ISSUE TITLE
Не приходят уведомления о релизах на Android 13

### ISSUE THREAD

**Issue by userkilled** [anilibria/anilibria-app#213]
Использовал ранее 10 версию системы, уведомления приходили и приходят, а вот на новый смартфон не приходят уведомления от приложения. Что может быть не так?

Версия приложения 2.13 работает в рабочем профиле. Другое ПО ведёт себя нормально

**Comment by RadiationX** [comment]
Какая модель смартфона?

**Comment by userkilled** [comment]
Google Services установлены, Google Play сообщает, что устройство сертифицированно 
Модель: Oukitel WP28 (2023)

**Comment by RadiationX** [comment]
Честно, первый раз вижу, чтобы обращались с подобной проблемой.
1. Приложению выдано разрешение на показ уведомлений?
2. В настройках внутри приложения уведомления не отключены?

**Comment by userkilled** [comment]
Да, было включено. Переключил снова все ползунки. Если что, то я в данном приложении переносил данные просмотренных релизов без аккаунта.

**Comment by userkilled** [comment]
Приложение в основном профиле тоже находится, тоже ничего не шлёт из уведомлений

**Comment by RadiationX** [comment]
Ну уведомления к аккаунту никак не привязаны. Просто общая рассылка на всех.
В общем странная ситуация, если само не починится в течении пары дней, то можно будет списаться в телеге, поскидываю дебажные версии, посмотрю в чем дело.

**Comment by userkilled** [comment]
Я настолько часто этим пользуюсь, что сама стема должна понимать, что это убивать нельзя. Она не страдает той ерундой, что делает 10 версия на другом смартфоне. Хотя приходят уведомления туда исправно. Фантастика какая-то

**Comment by userkilled** [comment]
А как насчёт того, чтобы всё это сделать через гитхаб? Или часто пишут

**Comment by RadiationX** [comment]
Да там в том то и дело, что  от приложения не так много зависит. 
Гугл сервисы сами пробуждают приложение и запускают показ уведомления. Главное, чтобы было разрешение на показ уведомлений.
--------------
Можно и здесь "подебажить", но в тележке это всё просто оперативнее можно сделать.

**Comment by userkilled** [comment]
![Screenshot_anilibria](https://github.com/user-attachments/assets/ecc94bea-eb0e-4499-bfa2-19f6b7302d96)
Так, в основном профиле прилетело уведомление, значит нужно попробовать их переподключить. В рабочем профиле попробую так же

**Comment by userkilled** [comment]
Сейчас их переподключить, запретил и снова разрешил, в настройках системы, и переподключил внутри приложения. Отпишусь о результатах, когда будет новый релиз выпущен

**Comment by userkilled** [comment]
Не знаю в чём дело, но уведомление в рабочем приложении нет. Хотя, в ТГ, три минуты назад появился релиз, хотя, может с задержкой. 
Не могу получить уведомление, не понимаю почему.

**Comment by userkilled** [comment]
Давайте попробуем отдебажить, что там такое не так может быть. Мне нужно будет как-то лично собирать это приложение?

Я его установлю в рабочий профиль. Так, на заметку

**Comment by userkilled** [comment]
![Screenshot_20241122-134412](https://github.com/user-attachments/assets/2549f989-5294-46d3-9b87-4dd2f3aef974)
Прилетело, но в данный момент оно было на переднем плане, а не в фоне. Буду смотреть дальше. Если так подумать, то может ошибка была в самих GMS, что не позволяла обработать уведомления, просто банки используют rustore push.
Интересно, а будут ли интегрироваться другие сервисы push?

**Comment by RadiationX** [comment]
Ну может быть какая-то особенность работы gms с разными профилями в андроиде. Давайте пока понаблюдаем как оно дальше работать будет.

**Comment by userkilled** [comment]
![Screenshot_20241122-180058](https://github.com/user-attachments/assets/4a891245-8806-4fc4-8b4c-fe69e095a49a)
Ну что, походу буду потом в Google звонить, что у меня уведомления не приходят 🤣
