### ISSUE TITLE
Login screen

### ISSUE THREAD

**Issue by dragoangel** [anilibria/anilibria-app#3]
1. На экране входа 3 поля:
Login, Password и TOTP -это ломает работу любого автозополнения. TOTP должен быть на отдельном экране после логина и пароля. И с вашей системой что он не при поставторизации спрашивается, то получается с кнопкой пропустить ТОТР, но правильней конечно не спрашивать его у тех у кого его нет.
2. Totp: не секретное поле - его не нужно хайдить, а что самое важное: в него нужно вставлять скопированый текст - сейчас это сделать нельзя, авторизация превращается в ад. Как опция: если буфер не пуст, в нем текст из 6 знаков и состоит только из цыфр то можно сразу с буфера всавлять в поле ТОТР - ибо это он.

**Comment by RadiationX** [comment]
Спустя два года я понял о чем идёт речь. Хорошее замечание, исправим

**Comment by dragoangel** [comment]
Надо было сказать, я бы как то скринами бы намекнул :)

**Comment by RadiationX** [comment]
По идеи в этом релизе было исправлено.
На экране авторизации только логин и пароль, а otp на отдельном экране.
https://github.com/anilibria/anilibria-app/releases/tag/2.7.0
