### ISSUE TITLE
Дублирование на телевизоры samsung не работает

### ISSUE THREAD

**Issue by AAAYaKo** [anilibria/anilibria-app#32]
(Сравнение с приложением anixart, как источник видео из anilibria)
И там и там выбран, как внешний плеер стандартный плеер samsung
И там и там включаю дублирование "SmartView"
Дальше разворачиваю изображение с телефона

- Anixart - перезагрузит видео, выдаст сообщение, что кодек не поддерживается и включается дублирование, нажимаю ок и видео на телеке

-  Anilibria app - перезагрузит видео, ничего не скажет, выбросит с сообщением на телевизоре видео не поддерживается, видео не запустить

**Comment by RadiationX** [comment]
Если еще актуально, проверьте пожалуйста как сейчас работает. На сервере проводились какие-то работы, возможно теперь заработало как надо?

**Comment by AAAYaKo** [comment]
Сейчас выбрасывает с ошибкой подключения сети
С сетью проблем нет
Повторялось вегда в разное время

**Comment by AAAYaKo** [comment]
Вроде какое-то время работало, но сейчас внешний проигрыватель вообще убрали, как функцию
