### ISSUE TITLE
Как установить на телевизор Samsung с Tizen OS

### ISSUE THREAD

**Issue by ScrudgMcDack** [anilibria/anilibria-app#34]
Есть ли возможность установки на Телевизор Samsung c Tizen ОS на борту?
Возможно, уже есть проверенные способы или готовые сборки?
Попробовал через Tizen Studio просто перепаковать исходники в перевариваемый данной осью дистрибутив.
Но, с наскоку не выходит - проект собираемся, приложение устанавливается, но при запуске сообщает, что внутри пустой шаблон.

**Comment by RadiationX** [comment]
Больше этим не занимались?
Есть более детальная информация об ошибке? Возможно просто в приложении для тв что-то сломал, т.к. давно его не собирал, хотя проводился рефакторинг, который мог что-то сломать.

**Comment by ScrudgMcDack** [comment]
Ошибок никаких не возникает: ни на этапе сборки, ни при установке в TV. А, вот при запуске единственное сообщение выдается, что проект пуст.
Да, пробовал ещё иначе перепаковать - разложить исходники в директории, как предложено шаблоном проекта и просто удалял директории по умолчанию и заменял их содержимым apk. Но, безрезультатно.
Вобщем, если вдруг вам это интересно, загляните в Tizen Studio. У вас знаний в разработке таких приложений гораздо больше - возможно, ларчик открывается просто.

**Comment by RadiationX** [comment]
Всё-таки портировать аппку под другие платформы tizen или webos будет сложно и нецелесообразно
