### ISSUE TITLE
[Предложение] Кнопка Пропустить (Skip)

### ISSUE THREAD

**Issue by phoriah** [anilibria/anilibria-app#45]
Прошу добавить кнопку скип (пропустить) для опенинга (интро) и эндинга (аутро) в плеере.
И сделать длину скипа настраиваемой. Либо, чтобы она задавалась авто под каждое Аниме, но тогда должно комьюнити постараться или владельцы, чтобы длина была правильной на каждом Аниме. 
Можно сделать систему, где пользователи отправляют предложение с таймингами и потом после проверки они становятся официальными и доступны всем (либо без проверки сразу для всех)

Вот хороший пример, где уже есть такая система:
https://jut.su/neon-evangelion/episode-20.html

Спасибо,
P.

**Comment by RadiationX** [comment]
Вроде бы на сайте это уже сделано и тайминги заполнены как минимум для актуальных релизов.
В мобильном приложении тоже добавим)

**Comment by RadiationX** [comment]
Сделано в мобильной аппке, будет в следующем релизе
