### ISSUE TITLE
[Вопрос] Андроид 4.4

### ISSUE THREAD

**Issue by greendevilll** [anilibria/anilibria-app#66]
При себе имею андроид tv на базе андрюхи 4.4 . 
При установке через апк, пишет про "синтаксическую ошибку". Всё перепробовал, декомпилил, через архив. Однако мобильная версия работает стабильно. Почему так?

**Comment by RadiationX** [comment]
Здравствуйте. У AndroidTV приложения минимальная поддерживаемая версия - андроид 5.0.
У мобильного приложения со следующего релиза тоже будет минималка 5.0 или 6.0, пока не решил.

Поддержка андроид 4.4 местами достаточно замороченная

**Comment by greendevilll** [comment]
лол, пришлось докупать приставку на 7 чтобы заработало) спасибо за ответ
