### ISSUE TITLE
Перенос "Скипа" опенингов/эндингов на android tv

### ISSUE THREAD

**Issue by dd194** [anilibria/anilibria-app#81]
Не так давно обновляли мобильную версию клиента. Просьба перенести функционал Скипа на тв-боксы

**Comment by RadiationX** [comment]
На той неделе пытался добавить скипы, но не получилось, слишком хитрозамороченно сделан плеер.
Так что эту задачу отложил до тех пор пока не появится идеи как это можно реализовать

**Comment by RadiationX** [comment]
Реализовано: https://github.com/anilibria/anilibria-app/releases/tag/tv-1.1.0
