### ISSUE TITLE
Добавьте свое приложение на f-droid

### ISSUE THREAD

**Issue by OmlineEditor** [anilibria/anilibria-app#9]
Нужно увеличить охват аудитории. Добавьте свое приложение на сайт https://f-droid.org/
Запрос на добавление можно сделать тут: https://gitlab.com/fdroid/rfp/issues/

Если у Вас есть необходимые технические навыки, можете самостоятельно собрать нужные метаданные и добавить их в репозиторий F-Droid Data. Это значительно ускорит публикацию приложения. https://gitlab.com/fdroid/fdroiddata/blob/master/CONTRIBUTING.md

**Comment by RadiationX** [comment]
Есть сомнения, что фдроид даст существенный прирост аудитории.
Где-то есть актуальная статистика пользователей фдроид? И на сколько вообще имеет смысл этим заморачиваться? Нужна статистика

**Comment by OmlineEditor** [comment]
F-Droid никогда не вел статистику и вести ее не будет. Это его политика - политика анонимности и конфиденциальности. С течением времени все больше людей заботятся об анонимности и берегут свои личные данные. У меня многие знакомые качают программы именно с F-Droid и отказываются от программ с Google т.к. там телеметрии и слежки выше крыши. Заранее сказать какой прирост аудитории будет невозможно. Тут еще можно сыграть на том что Аналибрия выбрала сторону открытости и ничего не прячет в рукаве и стоит лицом к аудитории. Все приложения  F-Droid собираются из исходного кода, предварительно проверяются на наличие возможных проблем безопасности и конфиденциальности. Скажите аудитории что если вам доверился F-Droid и выложил в совем репозитирии вашу программу то вам можно доверять, вы чесные и открытые. Это больше PR компания будет, о ее результатах узнаем немного позже через полгода-год наверное.

**Comment by OmlineEditor** [comment]
F-Droid охватывает не только Россию, он для всего мира. Если вы в приложении добавите возможность смотреть аниме на японском с английскими субтитрами это привлечет и западную аудиторию. В Европе и Америке более суровые законы на просмотр и распространение аниме. Ваше приложение точно поможет смотреть аниме за рубежом. Вы же переводите аниме в основном с английсуого языка? добавьте английские субтитры при просмотре аниме и получите прирост аудитории с запада. Вы будите первая аниме компания которая еще и запад охватывает, а не только Россию. Поговорите с Люпином по этому поводу и удачи в развитии.

**Comment by RadiationX** [comment]
В fdroid приложение не будет выложено
