### ISSUE TITLE
Создание векторной иконки приложения

### ISSUE THREAD

**Issue by ThIsLinked** [anilibria/anilibria-app#92]
Здорова. Посматриваю аниме в этой озвучке, и вполне доволен. В качестве благодарности мог бы нарисовать векторную иконку приложения. А то сейчас единственная это растровая в 432 пикселей. Касаемо иконки, могу также сделать адаптивную и монохромную – в векторе конечно же.

Я сам модолел и иллюстратор на 4PDA, дела с подобным имею регулярно. Это типа моё резюме, что я не какой-то там чухонь :D

Если интересует, то пиши:

> Профиль на 4PDA – https://4pda.to/forum/index.php?showuser=9870529

> Телега – https://t.me/thislinked

**Comment by RadiationX** [comment]
Сорян, шо долго не заходил в issues. У нас уже есть векторная иконка) 
То, шо она в аппке не векторная - это я видимо не доглядел. Запишу в баги, исправлю

**Comment by RadiationX** [comment]
Будет исправлено в следующем релизе 2.9.x на днях

**Comment by ThIsLinked** [comment]
> @RadiationX 
> Сорян, шо долго не заходил в issues. У нас уже есть векторная иконка) То, шо она в аппке не векторная - это я видимо не доглядел. Запишу в баги, исправлю

О-о, ну в master'е я уже заметил, Неужто сбылось? Но я как уполномоченный настасканный старпёр немножко встрепну. Во-первых, ты поместил сам fore в клавалификатор v26. Кстати, я только заметил, зачем в квалификатор засунул, если у тебя нет аналога? Но это ладно, не важно в общем... Так, ну то, шо трассировка в 432 единиц – я так понял, что вы походу все страдаете этой болезнью, "чем выше, тем лучше". Потом, шо будут делать владельцы с 7.1 на борту и ниже?
<details><summary>На вот ЭТО пялиться?</summary>
<img src="https://github.com/anilibria/anilibria-app/assets/45180688/ab731548-b5f4-4835-947c-a09ce2b9893d" />
</details>
Не ну, сам смотри. Как говорится – бывалые себе шпаргалку сделают, да будут юзать, а новички-носовички будут бебру нюхать. Вот такие обыденные дела... Хм, по крайней мере на 4PDA, на котором я шарюсь.

Я что-то от темы отъехал... Ага, для Дроида 8 и выше ты занёс вектор для лаунчера. В то время, как и владельцы старых ведёр, вместе с ними в очередь с вопросами встают владельцы теликов,
<details><summary>где видят такое</summary>
<img src="https://github.com/anilibria/anilibria-app/assets/45180688/8d293d1b-d39c-4b6a-9d10-8ca2465c56ed" />
</details>Я уже не буду говорить о том, что это единственный экземпляр (с 180dp) и владелец телика с нативным XXXHDPI пойдёт лесом.

Монохром не столь важен, это чисто опционально. Хотя вроде хромированные их любят... Наверное, пока ты это прочёл, у тебя уже осела мысль о том, что я тут припёрся и начал втирать "ото херня, тут тоже херня, а вон там ещё обе херни". Просто решил немножко вложиться в дело, если его можно так назвать.

В общем, не буду большу кумарить голову. Если вдруг понадобится моя помочь с подгонами, рисовкой и бла-бла-бла, то обращайся. Ссыли я указал, так что в гости попадёшь.

**Comment by RadiationX** [comment]
1. В v26 поместил на всякий случай, чтобы гарантированно разграничить иконки, кароч шоб просто меньше путаницы было.

2. То, шо иконка 432*432 - издержки того, что иконки делаю в фигме отталкиваясь изначально от размеров 512*512 -  т.к. это основной размер для гуглплея/хуавейстора/рустора. Привычка так сказать.

3. Для всего, что ниже 8 андроида по дефолту генерятся растровые иконки. 

4. На счет теликов конечно нужно глянуть поменялось ли что-то, но когда в 2020 году делал всё это дело, то интерфейс андроид тв был ограничен максимум в fullhd и там не нужны были модификаторы dpi.
Типа на 2k/4k теликах, весь интерфейс всё-равно рендерился в мыльном fullhd. Но при этом именно видео могло выводиться в нативном 2k/4k.

5. Ну вектор было сделать не сложно, просто поверх растровой картинки path расставил да и всё. Как раз наверно минут за 5 и сделал.

**Comment by ThIsLinked** [comment]
> @RadiationX 
> В v26 поместил на всякий случай, чтобы гарантированно разграничить иконки, кароч шоб просто меньше путаницы было.

Ну вообще-то по правилам так не нужно делать. Ты при сборке получишь только Warning, он-то проект соберёт, но ничего хорошего не будет.

> @RadiationX 
> генерятся растровые иконки

М, а ты ничего не заметил? Т.к. ты впихнул его в v26, IDE при попытке собрать увидит, что minSdk меньше и сделает ему растровый аналог. Тут да, всё верно. Но ты кое-чего не учёл – у тебя-то foreground, он получит растровые аналоги. А где ты возьмёшь background, если он у тебя тянется только из mipmap-anydpi-v26 через color? Да и вообще, это бесполезно, ведь у твоего mipmap стоит v26, а значит ниже будет юзать mipmap-hdpi/ic_launcher.png

> @RadiationX 
> андроид тв был ограничен максимум в fullhd и там не нужны были модификаторы dpi

Я хз, что там было в 2020 году, но сейчас теликам чётко присваются DPI.

> @RadiationX 
> Ну вектор было сделать не сложно

Но что-то ты его не делал. Не важно, каким образом ты его делал – важен результат на выходе. Абсолютно нет смысла делать хорошо в редакторе и выводить в хламьё.

Кстати, я в Pull'е обновил пути на те два вектора, о котором ты писал. Соррян, про первый забыл, что там накладные контура, и объединение в один путь заставит пересикающиеся трассеры вычитывать друг друга. В редакторе слил в один и перезалил, теперь нормально. Второй тоже сделал (копированием, т.к. там слой один и тот же).
