### ISSUE TITLE
Перенос истории просмотров на новое устройство

### ISSUE THREAD

**Issue by minzdrav** [anilibria/anilibria-app#95]
Добрый день.
Купил новый телефон и хочу перенести историю просмотров и настройки. Скажите, где они сохраняются? Сам не смог найти.

**Comment by minzdrav** [comment]
Здравствуйте, @RadiationX 
Спасибо что ответили!
Да, я знаю что нет функции синхронизации. Я таску по ней и создавал :) Я догадываюсь почему её нет. Скорее всего нужна совместная работа минимум двух команд(разработчиков андройд приложения и апи), а в идеале всех команд работающими над всеми приложениями. Это сложнодостижимо.
Есть пара вариантов решения проблемы переноса истории просмотров для андройд приложения без привлечения других команд.
1) Можно перенести файл с историей просмотров из приватного хранилища. Хранить историю в приватном хранилище избыточно. Там нет ничего такого секретного. Но этот вариант не очень юзер френдли, потому что пользователям придётся искать этот файл.
2) Добавить функцию экспорта\импорта. Пара кнопок. Экспорт в json(или любой другой удобный для вас формат). Любой пользователь справится с переносом истории на новое устройство.

**Comment by BlackRandomCraft** [comment]
> Здравствуйте, @RadiationX Спасибо что ответили! Да, я знаю что нет функции синхронизации. Я таску по ней и создавал :) Я догадываюсь почему её нет. Скорее всего нужна совместная работа минимум двух команд(разработчиков андройд приложения и апи), а в идеале всех команд работающими над всеми приложениями. Это сложнодостижимо. Есть пара вариантов решения проблемы переноса истории просмотров для андройд приложения без привлечения других команд.
> 
>     1. Можно перенести файл с историей просмотров из приватного хранилища. Хранить историю в приватном хранилище избыточно. Там нет ничего такого секретного. Но этот вариант не очень юзер френдли, потому что пользователям придётся искать этот файл.
> 
>     2. Добавить функцию экспорта\импорта. Пара кнопок. Экспорт в json(или любой другой удобный для вас формат). Любой пользователь справится с переносом истории на новое устройство.

можно вообще сделать привязку к гугл диску и чтобы оно само синхронизировалось. так-же с тв версией, не приятно когда просмотренное не синхронизируется между устройствами

**Comment by Rimiro-EV** [comment]
Если кому надо, то есть рабочий способ переноса истории просмотра и настроек БЕЗ РУТА. Через резервную копию приложения и восстановление на другом телефоне. Я переносил с MIUI на HyperOS(почти одно и тоже) по видео www.youtube.com/watch?v=CBcGO7eSQ3w , выбрал только AniLibria App, резервную копию перекинул на новый телефон по том же пути и восстановил. Не знаю сработает ли на других оболочках или при переносе с одной оболочки на другую, но можете попробовать.

**Comment by RadiationX** [comment]
Добавил (пока только мобильное приложение).
Импорт/экспорт внутри приложение.
Так-же можно из других приложений открыть json файл и аппка его обработает.
https://github.com/anilibria/anilibria-app/releases/tag/2.11.0_RC_1
