### ISSUE TITLE
При нажатии на кнопку "авторизоваться" не чего не происходит.

### ISSUE THREAD

**Issue by nvd05** [anilibria/anilibria-app#98]
## Суть проблемы

+ Скорее всего проблема в событие клика по кнопке.

> Примечание:
> Проблема только на телефоне.
> На планшете все нормально.

## Телефон

![1000005928.png](https://github.com/anilibria/anilibria-app/assets/69719657/1a6b32b2-4a6f-4d3e-a1e3-6abb1529f2f9)

## Видео проблемы

https://github.com/anilibria/anilibria-app/assets/69719657/2e3fc3ef-5461-4609-a663-f82686a1e0b2

**Comment by RadiationX** [comment]
Странно как приложение попало в это состояние. Одновременно считает, что есть авторизация и что её нет. 
Пока не понимаю как это могло произойти, но постараюсь исправить

**Comment by RadiationX** [comment]
Будет исправлено в следующем релизе 2.9.x на днях

**Comment by nvd05** [comment]
> Странно как приложение попало в это состояние. Одновременно считает, что есть авторизация и что её нет. 
> Пока не понимаю как это могло произойти, но постараюсь исправить

Другими словами: вы хотите сказать, что приложение думает, будто авторизация была произведена ранее?

Примечание: приложение так себя вело с момента самой первой установки.

**Comment by RadiationX** [comment]
Да. Странно, конечно это всё.

**Comment by nvd05** [comment]
> Да. Странно, конечно это всё.

Возможно какая-то мелочь есть в коде, которая показывает себя со временем.

У меня часто есть ошибки в коде, когда работаю с обрезанием строки (должен быть +1, а ставлю -1).

Хотя у вас в данном случае - состояния (реализованные скорее всего через внутреннюю базу данных) и по факту ошибиться при написании очень сложно.

**Comment by RadiationX** [comment]
Небольшое уточнение, т.е. вы в аппке ни разу не авторизовывались, но всё-равно возникла эта проблема?

Можете пожалуйста проверить этот билд: https://drive.google.com/file/d/1mSFw2frNzSGju4c0QN4Jd6QPXH8Dz_-E/view?usp=sharing

**Comment by nvd05** [comment]
![1000007710.png](https://github.com/anilibria/anilibria-app/assets/69719657/bd01d946-42f5-4fc0-b5b3-f65b2492c3ce)

Работать стало нормально.
Не подскажете что исправили в коде?

**Comment by RadiationX** [comment]
Да именно оно. Нужно было вынести проверку на 401 в глобальный обработчик. 
Ну и плюс косяк в том, что раньше при 401 кукисы не чистились.
